### ISSUE TITLE
jQuery-contextMenu is looking for a new maintainer

### ISSUE THREAD

**Issue by rodneyrehm** [swisnl/jQuery-contextMenu#257]
I haven't used the plugin in ages and haven't had the time to follow up on the issues and PRs in a long time now.

The website is seeing 35k page views per month, github registers another 7.4k - there still seems to be interest in this plugin.

I may assist in the transition and I may serve as some sort of guide if that is required. I will, however, not contribute any code. The project may stay in the medialize organization or move to your user/org - I don't mind either way. I'm handing over the entire project.

**Comment by bbrala** [comment]
It seems there not many who are willing to commit the time and effort to do this, i would be interested in making this happen with our teams. I've sent you an email with some information.

**Comment by rodneyrehm** [comment]
@bbrala and me have been talking about moving the project over to @swisnl. We've decided on a plan how to transfer the repository to its new home without breaking all the links pointing to its old home.

I guess the transfer will be completed within the week.

:)

**Comment by richpri** [comment]
Good luck. And I am glad to see this project reactivating.
I  only wish that I had the jquery expertise to contribute code.
I would be happy to be a tester of development releases.
I may also be able to help with documentation.

**Comment by bbrala** [comment]
I'd like to tell you guys a little bit about myself and the company i work for. My name is Björn Brala, lead developer at SWIS (http://www.swis.nl). SWIS is a Dutch web design company with around 30 employees. We have existed since 1999 and still going strong. 

Our company uses this plugin for our CMS and for several projects and rather not see it die a slow death. To achieve this we will take over maintaining this plugin. We are just looking to keep this plugin alive and well, and feel we can use some of our resources to sustain its life for the future.

First step is to transfer, which should be soon, after the migration is completed sucessfully we will start working through the backlog of issues and pull requests.

Also, thank you @rodneyrehm for making this plugin, without you this wouldn't have been possible.
