### ISSUE TITLE
jQuery second contextMenu don't show properly

### ISSUE THREAD

**Issue by germanmartin** [swisnl/jQuery-contextMenu#293]
Try it: http://jsfiddle.net/oprkvys1/3/

Make right clic in the green square and you will get "Miami Florida"
Make right clic outside (in blue background) and you will get "Irak Afganistan"
Then right make clic in the green square again and you will NOT get "Miami Florida", you will get "Irak Afganistan"

My original issue was closed marked as resolved but it's not. https://github.com/swisnl/jQuery-contextMenu/issues/238

**Comment by bbrala** [comment]
Hi @germanmartin,

I'm sorry i appearantly overlooked the problem when testing. It seems it just repositions. You can fix this by setting the reposition option to false.

http://swisnl.github.io/jQuery-contextMenu/docs.html#reposition

This will rebuild the contextMenu instead of just moving it.

http://jsfiddle.net/oprkvys1/4/

The behaviour is still a bit weird, but this will enable you to use it without a problem.

Original issue #238

**Comment by germanmartin** [comment]
Thank you so much! it works!
reposition:false,

**Comment by germanmartin** [comment]
Can you close this issue? 
Thanks!!

**Comment by bbrala** [comment]
Glad to hear it! Going to keep it open for now since it is kind of weird behavious that might need to be fixed, there is a PR #251 that might be related.
