### ISSUE TITLE
Support HTML as content for the name of an item

### ISSUE THREAD

**Issue by bbrala** [swisnl/jQuery-contextMenu#302]
As discussed in #252 a way to add HTML as an item that plays nicely with the different item types.

**Comment by arai-a** [comment]
there could be 2 ways to solve it:

1. Different property for HTML
  If `item.html` property exists, call `.html(item.html)` instead of `.text(item.name)`

2. Flag property to mark it as HTML
  If `item.isHTML` property is true, call `.html(item.name)` instead of `.text(item.name)`

in both way, property name is just a draft, there could be better name.

The problem is that there is already `item.type == 'html'` with `item.html` property for content.  It should be nice to make these 2 types clearly distinguishable.

**Comment by brassard** [comment]
Proposed a PR #388 to address this issue.

**Comment by brassard** [comment]
I believe that this issue is resolved with the now-merged PR #388.

**Comment by bbrala** [comment]
Yes! :) I went through the issues, but didnt go back enough. Thanks
