### ISSUE TITLE
Position: how to get mouse location

### ISSUE THREAD

**Issue by r02b** [swisnl/jQuery-contextMenu#355]
I couldn't find any reference to how to get the current mouse location from the position functions (the x,y provided are not referencing that).

Thanks!

**Comment by bbrala** [comment]
The library doesn't pass the original mouse event around, so you can't do that.

**Comment by r02b** [comment]
I'm trying to fix an error - the location of the menu has gone crazy on my app. I'm opening it from a dialog, an for some reason the location of the context menu is all over the place :\

**Comment by bbrala** [comment]
Any chance you can create a demo page with the error? For example on jsfiddle?

**Comment by r02b** [comment]
Yes, will provide one shortly.

**Comment by Schadows** [comment]
I have the same problem, and used the same kind trick to replace initial positioning.
In my case, the context menu is used on SVG element which is scaled (viewbox != from viewport) in a div somewhere in the page. the plugin seems to doing the computation wrong because it doesn't appear where I clicked (which is strange because positioning it at event.pageX, event.pageY should do the trick I suppose, but I must have missed something).

I worked around this by doing this : 
I use the "build" option to dynamically create the menu items (because I need them dynamic ^^). The callback for the "build" does pass the original event, so I can use that to create the "position" callback which will be included in the response.
I also need to set "reposition" to false to ensure the build is called each time otherwise the "event" used in the position callback will be wrong.

I agree, it's far fetched, but since I already use dynamic context menu, that doesn't change that much.

The problem I discovered today is, by setting the position of the menu using the position callback and executing the opt.$menu.css({left: event.pageX, top: event.pageY}) and not using the initial positioning, you loose the auto correction of positioning when opening the menu or its sub menus close to the border of the window.

**Comment by Schadows** [comment]
here is an jsfiddle of my problem :
https://jsfiddle.net/zo9v372w/

and here is how I worked around it :
https://jsfiddle.net/0y2mo53j/1/

**Comment by Schadows** [comment]
I adjusted the menu position to keep it in the window by copying the code from the original "position" function (the only thing which is wrong is the x,y it is based on), but that leaved me with the submenu positionning.

I discovered there is a "positionSubmenu" parameter/callback that you can set (like "position" or any other parameter) which lets you determine the submenu position based on the menu position.
If jquery-ui position isn't there, the submenu is displayed a the left even if it left the screen. So I applied the same logic that was existing for the menu position and that did the trick.

**Comment by bbrala** [comment]
Can you recheck against master? There were some changes to the positioning. 

Also see you use SVG as the trigger element, i assume you have an jQuery later than 1.12 or 2.2?

**Comment by Schadows** [comment]
The jsfiddle I posted above to illustrate the problem was already pointing to the master, and is working fine now. I even checked that the subMenu positioning was working exactly as when clicking on a non-svg element.

Thank you d(^_~ )

I use jquery 2.1.4.

**Comment by bbrala** [comment]
Glad to hear it!
