### ISSUE TITLE
Item order is inverted in Chrome

### ISSUE THREAD

**Issue by tiagof** [swisnl/jQuery-contextMenu#45]
Hi,

for some reason the item order is inverted in chrome (version 18.0.1025.168 m).
Both IE and Firefox show the items in the order they are declared.

I assume there is no option/parameter to define the order (at least i couldn't find it in the api).

Is it a plugin issue or chrome's fault?

some SS:
http://dl.dropbox.com/u/6551/ssChrome.png
http://dl.dropbox.com/u/6551/ssIE.png

**Comment by fake-name** [comment]
I'm curious how this is fixed, because reading the linked question above, apparently there isn't really a way to work around the issue. 

AFICT, basically the only way to actually solve this is to not use an object to pass in the items to be placed into the menu. It might "work" right now, but it's working by virtue of an implementation artifact, rather then because it's correct.

**Comment by bbrala** [comment]
Yeah for now it is indeed relying on the behaviour that reordering only happens when the keys are numeric. This might not be ideal, but if this is changed, it needs to be backward compatible. 

I wouldn't mind the plugin to accept a Map and get values with a getter then. I would recommend making a new issue with the request for the items to accept a Map as definition.

**Comment by JamoCA** [comment]
This tripped me up today too. (12 years later) I was dynamically generating numeric strings for some item keys and the menu became unsorted after the first number strings were added to the menu.  I fixed this by prefixing the keys with a string + underscore and then sanitized the key value during the callback.

**Comment by hybridwebdev** [comment]
> This tripped me up today too. (12 years later) I was dynamically generating numeric strings for some item keys and the menu became unsorted after the first number strings were added to the menu. I fixed this by prefixing the keys with a string + underscore and then sanitized the key value during the callback.

It's 2024 and you're still using jQuery? Man I feel bad for whoever pays you to do development for them.

**Comment by JamoCA** [comment]
.@hybridwebdev Thanks for the helpful & insightful feedback.  LOL.  I can only assume by way of contrast that you use native JavaScript for everything you do. Very, very impressive.  Would you care to share which superior library you are using for JavaScript-based context menus?

This issue was reported 12 years ago.  While I haven't been using this library for 12 years, I was attempting to indicate that this issue is 12 years old, still exists and the behavior of the numeric object keys being oddly sorted still exists. I'm thankful for posts like this that enable me to identify that it's a known, and it's easy to work around.

My clients are quite satisfied. I've been developing web applications since '97 and don't use PHP or WordPress. While I primarily focus on the server-side, I do write some JavaScript and have found the jQuery library has stood the test of time when many other companies, technologies & libraries I've used or considered have been either replaced, are currently defunct or are deprecated.  jQuery v4 Beta was just released, and I prefer "using what works" rather than investing time learning each new fad in hopes that it will solve some problem that I don't have.

>According to Stack Overflow's survey, 22.87% of developers still use JQuery, it's the third most popular web framework and one of the most starred repositories on GitHub.
>https://www.learnenough.com/blog/what-is-jquery
