### ISSUE TITLE
Focus not set on element when right click

### ISSUE THREAD

**Issue by dbarrett84** [swisnl/jQuery-contextMenu#482]
I have added the context menu on a `table` element within a `contenteditable` area.

When I right click it shows the correct context menu, **BUT** the selected element is not updated because the right click has stopped propagation and therefore my options in the menu are being applied to the wrong element.

See for example:
https://jsfiddle.net/dbarrett84/s4j64Lo7/1/

Right click in the column heading and then in caption, cursor doesn't move to the caption it stays in the column heading cell.

**Comment by bbrala** [comment]
Hmm, i see what you mean. Seems the problem is propably [this code](https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L453-L457). It doesn't really click, but finds the target based on the position.

I might be able to do that differently so it wont stop there without breaking the code. I'll try and have a look soon.

**Comment by robfenlon** [comment]
Hi, I have a PR up that will fix this issue for contenteditable elements:
#486 
Thanks!

**Comment by bbrala** [comment]
Thanks for making PR available for this. @dbarrett84 think you can have a look if that PR fixes it for you?

**Comment by dbarrett84** [comment]
Ya looks good, fixes my issue.

**Comment by bbrala** [comment]
Merged your PR, thanks!

**Comment by dbarrett84** [comment]
Excellent, thanks very much Björn and Rob!
