### ISSUE TITLE
Fontawesome 5 (Pro?) support broken

### ISSUE THREAD

**Issue by reFX-Mike** [swisnl/jQuery-contextMenu#638]
When using the CSS/webfont for FontAwesome 5.0 (I've used Pro, but it might affect the non-pro version as well), the icons do not show up at all.

I've managed to supply a function that returns the correct class names, but then the icons have a large margin/padding on the left and the menu-item text itself loses its font and looks like some old school font with sarifs.

**Comment by LeonGreeff** [comment]
I have the same issue. I will come back to you if I found a solution.

**Comment by bbrala** [comment]
I wonder what the best solution would be. The current setup is really just adding an class to the item. 

Perhaps the best option would be another icon setting (iconHtml?) in which you can put a bit of html. Which enables things like `<i class='fas fas-confirm'></i>`. And would enable usage of different icons. Especially since Fa5 now also supplies SVG alongside the old font approach.

**Comment by wimZ** [comment]
Same issue here.  The fa icons show huge.

Fontawesome has a shim js, but that does not solve it. 

Fal;ling back to native icons for now

**Comment by dschueler** [comment]
same here...FA BROKEN   ..all good in the rest of my page..NOT good in context menu
 
![2018-06-23_08-41-31](https://user-images.githubusercontent.com/371030/41809860-b1546936-76c2-11e8-906f-0afe32bc091f.png)

**Comment by IMS-Global** [comment]
We recently upgraded to FontAwesome 5 Pro and all Icons are broken. As mentioned above the icon sets for fa, fal, and fab icons are no longer displaying. Unable to fallback to previous version of FontAwesome. Looking for a work-around to fix the problem.

**Comment by bbrala** [comment]
This issue is is a duplicatie of #593, i've created a branch with a fix for Font Awesome 5 support.
