### ISSUE TITLE
get the element where the context menu was shown on right click

### ISSUE THREAD

**Issue by Jogii** [swisnl/jQuery-contextMenu#755]
I need to show different context menu items based on the file/folder being right clicked, i have the required info binded to the data attribute of the element being right clicked. but sadly i cannot retrieve the same using the jQuery-contextMenu.. :(
This is very basic, can anyone help me out with this?

**Comment by ArthurD** [comment]
For **version 2** (the current version), the code is documented quite well. 

Here's a working snippet that will display the context-menu's "target" (whatever was right-clicked) item's ID in the console upon clicking on an item.  It also added the "highlighted" class to the target.

`
    <script type="text/javascript">

    $(function() {
        $.contextMenu({
            selector: '.source',
            callback: function(itemKey, opt){
              // Alert the key of the item and the trigger element's id.
              console.log("Clicked on " + itemKey + " on element " + opt.$trigger.attr("id"));
              opt.$trigger.addClass(".highlighted");
              // Do not close the menu after clicking an item
              return false;
            },
            items: {
                "edit": {name: "Edit", icon: "edit"},
                "cut": {name: "Cut", icon: "cut"},
               copy: {name: "Copy", icon: "copy"},
                "paste": {name: "Paste", icon: "paste"},
                "delete": {name: "Delete", icon: "delete"},
                "sep1": "---------",
                "quit": {name: "Quit", icon: function(){
                    return 'context-menu-icon context-menu-icon-quit';
                }}
            }
        });
    });

    </script>`

Since you want to _conditionally_ change your menu items based on what was clicked, you'll use the same concept but instead of using the callback named "callback", you will instead most likely want to use the "build" callback.  See the [documentation for the build option](http://swisnl.github.io/jQuery-contextMenu/docs.html#build).

[This specific example](https://swisnl.github.io/jQuery-contextMenu/demo/dynamic-create.html) shows how to use the 'build' callback to, well, build the menu on-the-fly -- and you can use the same concept about to figure out what the 'target' element was.  

Hope that helps!  :)

**Comment by ArthurD** [comment]
I happened to need something very similar to what you asked for, so here's a "fully working" example (minus the HTML parts).  It includes conditional add of items to the context menu based on whatever logic you want to use -- and you have the "target" object, so you can alter options based on what was right-clicked.

**Full example here:**
https://gist.github.com/ArthurD/aa1ee2cd8029f9ad16070754339055c0
